name: cclib

on: [push, pull_request]

jobs:
  linux-python:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8']
    steps:
    - name: Install swig
      run: |
        sudo apt-get update && sudo apt-get install -y -qq swig
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} with conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge, psi4
    - name: Install dependencies
      shell: bash -l {0}  
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest numpy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install conda deps
      shell: bash -l {0}  
      run: |
          conda config --set always_yes yes --set changeps1 no --set channel_priority flexible
          conda info -a
          conda install ci-psi4 openbabel psi4
          conda install pytest pytest-cov codecov pytest-shutil
          python -m pip install h5py pyscf
          python -m pip install git+https://github.com/theochem/iodata.git
          conda list
    - name: Install cclib
      shell: bash -l {0}  
      run: |
          which python
          python -m pip install .
    - name: Before Test
      shell: bash -l {0}  
      run: |
          which python
          export DOCS_BRANCH_NAME=master
          export DOCS_REPO_NAME=cclib.github.io
          export DOCS_REPO_OWNER=cclib
          export DOCS_ROOT_DIR="${GITHUB_WORKSPACE}"/doc/sphinx
          export DOCS_BUILD_DIR="${DOCS_ROOT_DIR}"/_build/html
          export THEME_DIR="${DOCS_ROOT_DIR}"/_themes
          install -dm755 "${THEME_DIR}"
    - name: Test with pytest
      shell: bash -l {0}  
      run: |
          which python
          env | sort
          bash .github/scripts/run_pytest.bash
          bash .github/scripts/build_docs.bash
