name: cclib

on: [push, pull_request]

jobs:
  linux-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7']
    steps:
    - name: Install SWIG and Git
      run: |
        apt-get update && apt-get install -y -qq git swig
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} with conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        miniconda-version: "latest"
        python-version: ${{ matrix.python-version }}
        channels: conda-forge, psi4
    - name: Install conda deps
      shell: bash -l {0}
      run: |
          conda config --set always_yes true --set changeps1 false --set channel_priority flexible --set quiet true
          conda info -a
          conda install ci-psi4 psi4 openbabel pytest-cov pytest-shutil h5py
          python -m pip install pyscf
          python -m pip install git+https://github.com/theochem/iodata.git
          conda list
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Install cclib
      shell: bash -l {0}
      run: |
          which python
          python -m pip install .
    # - name: Before Test
    #   shell: bash -l {0}
    #   run: |
    #       which python
    #       export DOCS_BRANCH_NAME=master
    #       export DOCS_REPO_NAME=cclib.github.io
    #       export DOCS_REPO_OWNER=cclib
    #       export DOCS_ROOT_DIR="${GITHUB_WORKSPACE}"/doc/sphinx
    #       export DOCS_BUILD_DIR="${DOCS_ROOT_DIR}"/_build/html
    #       export THEME_DIR="${DOCS_ROOT_DIR}"/_themes
    #       install -dm755 "${THEME_DIR}"
    - name: Test with pytest
      shell: bash -l {0}
      run: |
          which python
          env | sort
          bash .github/scripts/run_pytest.bash
    #       bash .github/scripts/build_docs.bash
